baseURL = "https://veriqtas.github.io/"
languageCode = "en-us"
title = "VERIqTAS workshop 2026"
theme = "hugo-scroll"

[params]
  description = "March 23–25, 2026 • ENS de Lyon"

[menu]
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 1

  [[menu.main]]
    name = "Program"
    url = "#program"
    weight = 2

  [[menu.main]]
    name = "Participants"
    url = "#participants"
    weight = 3

  [[menu.main]]
    name = "Venue"
    url = "#venue"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 5
